name: Components
description: Custom version of Components for ConflictPE
authors:
- Jack Noordhuis
version: 0.0.1_ALPHA
load: STARTUP
main: \core\Main
api:
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6

permissions:
  vipslots:
    description: "Main vip slots permission node"
    default: op
    children:
      vipslots.bypass:
        description: "Allows you to join the server when full"
        default: op
  staffchat:
    description: "Main staff chat permission node"
    default: op
    children:
      staffchat.toggle:
        description: "Allows you to toggle the staff chat"
        default: op
  hologram:
    description: "Main hologram permission node"
    default: op
    children:
      hologram.command:
        description: "Allows you to use the hologram command"
        default: op