# Conflict Network CorePlugin - Settings.yml configuration file
settings:
  # Enable test commands and in-dev features
  testing-mode: false
  # Print debug messages in console
  enable-debug: false
  # Gamemode of the server (used to make sure players don't try and transfer to a server they're on)
  gamemode: prison
  # Time until the server automatically restarts in seconds
  restart-time: 3600
  # List of servers available through the play command
  servers:
    factions: fac.conflictpe.net
    prison: psn.conflictpe.net
  # Network sync information
  network:
    # Should we enable network sync?
    # The server will still submit data but it won't read any
    # ** Not implemented yet! **
    enable: true
    # Server type/node
    # ** Do not input any value here without checking with database and/or other staff first or the server won't sync properly **
    node: "Hub"
    # Server number/id
    # ** Do not input any value here without checking with database and/or other staff first or the server won't sync properly **
    id: 1
    # Time in ticks in which the server should sync with the database
    sync-interval: 20
  database:
    host: "172.106.17.114"
    user: "12"
    password: "0d5b45c4ee"
    name: "12"
    port: 3306